### PR TITLE
CODEOWNERS file added

### PR DESCRIPTION
**Pull request by PratyushChauhan**
# Description
Said file was added

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Reviewing this right now, let's see...

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Oh looks like the `CODEOWNERS` file I gave you is outdated. It has **Carl listed**, but he's... no longer with the company. Could you **remove him from the file**, but not from our hearts, and push that change?

**Comment by PratyushChauhan** [comment]
Done

**Comment by PratyushChauhan** [comment]
@vanessa-cooper

**Pull request closed without merging**
